config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :events do
    resources :guests
  end


  namespace :api do
    resources :guests, only: [:create]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :guests
  belongs_to :user
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :event

  after_create :send_favorite_emails

   private

   def send_favorite_emails
    GuestMailer.new_rsvp(self).deliver_now
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :destroy_session

  def destroy_session
    request.session_options[:skip] = true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html
  before_action :authenticate_user!, except: :show

  def index
    @events = current_user.events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = current_user.events.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    @event.save
    redirect_to @event
  end

  def update
    @event = current_user.events.find(params[:id])
    @event.update_attributes!(event_params)
    redirect_to @event
  end

  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy!
    redirect_to events_url
  end

  private
    def event_params
      params.require(:event).permit(:title, :description, :theme, :date, :host, :location, :image)
    end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :update, :destroy]

  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def new
    @guest = Guest.new
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def create
    @event = Event.find(params[:event_id])
    @guest = @event.guests.build(guest_params.merge(event: @event))
    if @guest.save
      render :recieved
    else
      render :error
    end
  end

  def update
    @guest = Guest.find(guest_params)
    @guest.update!(guest_params)
    redirect_to @guest
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy!
    redirect_to guests_url
  end

  private
    def guest_params
      params.require(:guest).permit(:name, :comment, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.haml
.well.bs-component
  = form_for @event, :html => {:class => 'form-horizontal'} do |f|
    - if @event.errors.any?
      #error_explanation
        %h2
          = pluralize(@event.errors.count, "error")
          prohibited this event from being saved:
        %ul
          - @event.errors.full_messages.each do |message|
            %li= message
    %fieldset
      %legend Event
      .form-group
        %label.col-lg-2.control-label Title
        .col-lg-10
          = f.text_field :title, class: "form-control"
      .form-group
        %label.col-lg-2.control-label Description
        .col-lg-10
          = f.text_area :description, class: "form-control", rows: "3"
      .form-group
        %label.col-lg-2.control-label Host
        .col-lg-10
          = f.text_field :host, class: "form-control"
      .form-group
        %label.col-lg-2.control-label Location
        .col-lg-10
          = f.text_field :location, class: "form-control", id: "location"
      .form-group
        %label.col-lg-2.control-label Date:
        .col-lg-10
          = f.datetime_select :date
      .form-group
        .col-lg-10.col-lg-offset-2
          = f.submit nil , :class => "button btn btn-info"

app/views/events/edit.html.haml
.container
  %h1 Editing Event
  = render 'form'
  = link_to 'Show', @event
  |
  \#{link_to 'Back', events_path}

app/views/events/index.html.haml
.container  
  %p.text-success#notice= notice
  %h2
    Your Events &nbsp; &nbsp; &nbsp;
    = link_to 'Create New Event', new_event_path, class: "btn btn-success btn-xs", data: {no_turbolink: true}
    %hr/
  - @events.each do |event|
    = link_to(event) do
      %h3= event.title
    %p.text-primary= event.description
  %br/

app/views/events/new.html.haml
.container
  .col-lg-6
    = link_to 'Back', events_path
    %br/
    = render 'form'

app/views/events/show.html.haml
.container
  %p#notice= notice
  %h2
    = @event.title
  %p
    = @event.description
  %p
    %strong Date:
    = @event.date.strftime("%I:%M%p, %A, %B %d, %Y")
  %p
    %strong Hosted by:
    = @event.host
  %p
    %strong Location:
    = @event.location
  - if current_user
    = link_to 'Edit', edit_event_path(@event), class: "btn btn-info btn-sm", data: {no_turbolink: true}
    &nbsp;
    = link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"
  %br
  = link_to 'Back', events_path
  - unless current_user
    %hr
    %h3 Confirm now:
    - @guest ||= @event.guests.new
    = render partial: 'guests/form'
  %hr/
  - if current_user
    %h3 Who's coming?
    %p.muted-text
      = pluralize(@event.guests.count, 'guest')
      attending so far...
    %br

app/views/guests/_form.html.haml
= form_for [@event, @guest] do |f|
  - if @guest.errors.any?
    #error_explanation
      %h2
        = pluralize(@guest.errors.count, "error")
        prohibited this guest from being saved:
      %ul
        - @guest.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_area :email    
  .field
    = f.label :comment
    %br/
    = f.text_area :comment
  .actions
    = f.submit

app/views/guests/_guest.html.haml
%h4
  %strong Name:
  = guest.name
%p
  %strong Email:
  = guest.email
%p
  %strong comment:
  = guest.comment
%hr

app/views/guests/edit.html.haml
%h1 Editing Guest
= render 'form'
= link_to 'Show', @guest
|
\#{link_to 'Back', guests_path}

app/views/guests/error.html.haml
%h3
%p something went wrong there. Please try to submit again.

app/views/guests/index.html.haml
%p#notice= notice
%h1 Listing Guests
%table
  %thead
    %tr
      %th Name
      %th Comment
      %th{:colspan => "3"}
  %tbody
    - @guests.each do |guest|
      %tr
        %td= guest.name
        %td= guest.comment
        %td= link_to 'Show', guest
        %td= link_to 'Edit', edit_guest_path(guest)
        %td= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Guest', new_guest_path

app/views/guests/new.html.haml
%h1 New Guest
= render 'form'
= link_to 'Back', guests_path

app/views/guests/recieved.html.haml
%h3 RSVP sent
%p
  great job! We're looking forward to having you!

app/views/guests/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @guest.name
%p
  %strong Comment:
  = @guest.comment
= link_to 'Edit', edit_guest_path(@guest)
|
\#{link_to 'Back', guests_path}

app/views/layouts/_header.html.haml
!!!
%html
  %head
    %title Rsvp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %script{:src => "https://maps.googleapis.com/maps/api/js?libraries=places", :type => "text/javascript"}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    .navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          = link_to "RSVP", root_path, class: "navbar-brand"
          %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #navbar-main.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li
              = link_to "events", events_path
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a#themes.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "themes"}
                - if user_signed_in?
                  %li
                    %a{:href => "../"} Account info
                  %li.divider
                  %li
                    = link_to "Sign out", destroy_user_session_path, method: :delete
                - else
                  %li
                    = link_to "Log in", events_path

app/views/layouts/application.html.haml
= render 'layouts/header'
= yield